env:
  browser: true
  es2021: true
  node: true
extends:
  - xo
  - plugin:vue/vue3-essential
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  vue/multi-word-component-names:
    - off
  prettier/prettier:
    - error
